package betess.presentation;

import betess.business.Aposta;
import betess.business.BetESS;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel Sousa
 * @author Tiago Alves
 */
public class DialogAposta extends javax.swing.JDialog {
    
    private BetESS betEss;
    private Aposta aposta;

    /**
     * Creates new form DialogAposta
     * @param parent
     * @param modal
     * @param b
     * @param a
     */
    public DialogAposta(java.awt.Frame parent, boolean modal, BetESS b, Aposta a) {
        super(parent, modal);
        this.betEss = b;
        this.aposta = a;
        
        initComponents();
        setup();
        
        this.setLocationRelativeTo(null);
    }
    
    private void setup() {
        DefaultTableModel model = (DefaultTableModel) this.jTableAposta.getModel();
        
        this.aposta.getEventos().values().forEach(e -> {
            model.addRow(new Object[] {
                e.getIdEvento(),
                e.getEquipaUm(),
                e.getEquipaDois(),
                this.aposta.getOdds().get(e.getIdEvento()),
                e.getEstado(),
                e.getResultado()
            });
        });
        
        this.jTableAposta.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAposta = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipa Casa", "Equipa Fora", "Odd Apostada", "Estado"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jTableAposta.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTableAposta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipa Casa", "Equipa Fora", "Odd Apostada", "Estado", "Resultado"
            }
        ));
        jScrollPane5.setViewportView(jTableAposta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAposta;
    // End of variables declaration//GEN-END:variables
}
