package betess.presentation;

import betess.business.Aposta;
import betess.business.BetESS;
import betess.business.Evento;
import javax.swing.DefaultComboBoxModel;

/**
 * 
 * @author Manuel Sousa 
 * @author Tiago Alves
 */
public class EventoDialog extends javax.swing.JDialog {
    
    private BetESS betEss;
    private Evento evento;
    private Aposta aposta;
    
    /**
     * Creates new form EventoDialog.
     * @param parent
     * @param modal
     * @param b
     * @param idEvento
     * @param a
     */
    public EventoDialog(java.awt.Frame parent, boolean modal, BetESS b, int idEvento, Aposta a) {
        super(parent, modal);
        this.betEss = b;
        this.aposta = a;
        this.evento = this.betEss.getEvento(idEvento);
        
        initComponents();
        setup();
        
        this.setLocationRelativeTo(null);
    }
    
    private void setup() {
        String equipa1 = this.evento.getEquipaUm();
        String equipa2 = this.evento.getEquipaDois();
        
        this.jLabelEquipaUm.setText(equipa1);
        this.jLabelEquipaDois.setText(equipa2);
        this.oddUm.setText(String.valueOf(this.evento.getOddUm()));
        this.oddX.setText(String.valueOf(this.evento.getOddX()));
        this.oddDois.setText(String.valueOf(this.evento.getOddDois()));
        this.estado.setText(this.evento.getEstado());
        this.resultado.setText(this.evento.getResultado());
        
        // Confirmar a existência dos elementos.
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxResultados.getModel();
        if (model.getIndexOf(equipa1) == -1 &&
            model.getIndexOf("EMPATE") == -1 &&
            model.getIndexOf(equipa2) == -1)
        {
            model.addElement(equipa1);
            model.addElement("EMPATE");
            model.addElement(equipa2);
        }
        
        if (this.betEss.getUser().equals("betadmin@betess.pt")) {
            this.estado.setEditable(false);
            //this.resultado.setEditable(true);
            this.resultado.setVisible(false);
            this.jPanelAddEvento.setVisible(false);
        } else {
            this.estado.setEditable(false);
            this.editaEstadoBtn.setVisible(false);
            this.editaResBtn.setVisible(false);
            this.jLabel3.setVisible(false);
            this.jComboBoxResultados.setVisible(false);
            this.resultado.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEvento = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelEquipaUm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelEquipaDois = new javax.swing.JLabel();
        oddUm = new javax.swing.JCheckBox();
        oddX = new javax.swing.JCheckBox();
        oddDois = new javax.swing.JCheckBox();
        jPanelAddEvento = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        editaEstadoBtn = new javax.swing.JButton();
        editaResBtn = new javax.swing.JButton();
        jComboBoxResultados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelEvento.setBackground(new java.awt.Color(36, 47, 65));
        jPanelEvento.setMaximumSize(new java.awt.Dimension(30000, 30000));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jLabelEquipaUm.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabelEquipaUm.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquipaUm.setText(this.evento.getEquipaUm());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");

        jLabelEquipaDois.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabelEquipaDois.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEquipaDois.setText(this.evento.getEquipaDois());

        oddUm.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        oddUm.setForeground(new java.awt.Color(255, 255, 255));

        oddX.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        oddX.setForeground(new java.awt.Color(255, 255, 255));

        oddDois.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        oddDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEquipaUm)
                    .addComponent(oddUm))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(oddX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oddDois)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(jLabelEquipaDois)
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEquipaUm)
                    .addComponent(jLabel2)
                    .addComponent(jLabelEquipaDois))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oddUm)
                    .addComponent(oddX)
                    .addComponent(oddDois))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelAddEvento.setBackground(new java.awt.Color(255, 102, 102));
        jPanelAddEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddEventoMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Avenir", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Adicionar Evento");

        javax.swing.GroupLayout jPanelAddEventoLayout = new javax.swing.GroupLayout(jPanelAddEvento);
        jPanelAddEvento.setLayout(jPanelAddEventoLayout);
        jPanelAddEventoLayout.setHorizontalGroup(
            jPanelAddEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddEventoLayout.setVerticalGroup(
            jPanelAddEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddEventoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanelEventoLayout = new javax.swing.GroupLayout(jPanelEvento);
        jPanelEvento.setLayout(jPanelEventoLayout);
        jPanelEventoLayout.setHorizontalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEventoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEventoLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jPanelAddEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanelEventoLayout.setVerticalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAddEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel1.setText("Estado");

        estado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel3.setText("Resultado");

        resultado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        editaEstadoBtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        editaEstadoBtn.setText("Alterar");
        editaEstadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaEstadoBtnActionPerformed(evt);
            }
        });

        editaResBtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        editaResBtn.setText("Alterar");
        editaResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaResBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addComponent(estado)
                        .addComponent(jLabel3)
                        .addComponent(editaEstadoBtn))
                    .addComponent(editaResBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editaEstadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editaResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAddEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddEventoMouseClicked
        if (this.oddUm.isSelected() && !this.oddDois.isSelected() && !this.oddX.isSelected()) {
            double odd = Double.valueOf(this.oddUm.getText());
            this.aposta.addEventoToAposta(this.evento, odd);
            this.dispose();
        } else if (!this.oddUm.isSelected() && this.oddDois.isSelected() && !this.oddX.isSelected()) {
            double odd = Double.valueOf(this.oddDois.getText());
            this.aposta.addEventoToAposta(this.evento, odd);
            this.dispose();
        } else if (!this.oddUm.isSelected() && !this.oddDois.isSelected() && this.oddX.isSelected()) {
            double odd = Double.valueOf(this.oddX.getText());
            this.aposta.addEventoToAposta(this.evento, odd);
            this.dispose();
        } //else javax.swing.JOptionPane.showMessageDialog(this, "Apostas múltiplas não são permitidas!", "Aposta", 0);
    }//GEN-LAST:event_jPanelAddEventoMouseClicked

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        
    }//GEN-LAST:event_estadoActionPerformed

    private void editaEstadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaEstadoBtnActionPerformed
        this.betEss.alteraEstadoEvento(this.evento.getIdEvento());
        this.setup();
    }//GEN-LAST:event_editaEstadoBtnActionPerformed

    private void editaResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaResBtnActionPerformed
        String res = (String) this.jComboBoxResultados.getSelectedItem();
        
        //if (res.equals(this.jLabelEquipaUm.getText()) || 
          //  res.equals(this.jLabelEquipaDois.getText()) || 
            //res.equals("EMPATE"))
            this.betEss.novoResultado(this.evento.getIdEvento(), res);
       // else 
         //   javax.swing.JOptionPane.showMessageDialog(this, "Resultado desconhecido!", "Evento", 0);
    }//GEN-LAST:event_editaResBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editaEstadoBtn;
    private javax.swing.JButton editaResBtn;
    private javax.swing.JTextField estado;
    private javax.swing.JComboBox<String> jComboBoxResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEquipaDois;
    private javax.swing.JLabel jLabelEquipaUm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAddEvento;
    private javax.swing.JPanel jPanelEvento;
    private javax.swing.JCheckBox oddDois;
    private javax.swing.JCheckBox oddUm;
    private javax.swing.JCheckBox oddX;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
