package betess.presentation;

import betess.business.Apostador;
import betess.business.Evento;
import betess.business.Facade;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel Sousa
 * @author Tiago Alves
 */
public class JDialogNotifications extends javax.swing.JDialog {
    
    private Facade betEss;
    private Integer estatuto;

    /**
     * Creates new form JDialogNotificacoes.
     * 
     * @param parent
     * @param modal
     * @param betEss
     * @param estatuto
     */
    public JDialogNotifications(java.awt.Frame parent, boolean modal, Facade betEss, Integer estatuto) {
        super(parent, modal);
        this.betEss = betEss;
        this.estatuto = estatuto; 
        initComponents();
        
        // Verifica qual user em sessão.
        if (estatuto == 1)
            this.atualizaTabelaApostador();
        else if (estatuto == 2)
            this.atualizaTabelaBookie();
    }
    
    /**
     * Método atualizaTabelaApostador().
     * Atualiza a tabela de notificações no caso de o user em sessão
     * ser um Apostador.
     */
    private void atualizaTabelaApostador() {
        Apostador ap = this.betEss.getApostador(this.betEss.getUser());
        ArrayList<Integer> noti = ap.getNotifications();
        
        DefaultTableModel model = (DefaultTableModel) this.jTableEventos.getModel();
          
        noti.forEach(idAposta -> {
            double ganho = this.betEss.getGanhoEmAposta(idAposta);
            
            Collection<Evento> evs = ap.getApostas()
                    .get(idAposta)
                    .getEventos()
                    .values();
            
            evs.forEach(ev -> {
                model.addRow(new Object[] {
                    idAposta,
                    ev.getIdEvento(),
                    ev.getEquipaUm(),
                    ev.getEquipaDois(),
                    ev.getResultado(),
                    this.betEss.getResultadoApostado(idAposta, ev),
                    ganho
                });
            });
        });
    }
    
    /**
     * Método atualizaTabelaBookie().
     * Atualiza a tabela de notificações no caso de o user em sessão
     * ser um Bookie.
     */
    private void atualizaTabelaBookie() {
        Map<Integer, Map<Integer, Evento>> eventos = this.betEss.getBookieEventos();
        Evento evento;
        double ganho;
        int idAposta;
        
        DefaultTableModel model = (DefaultTableModel) this.jTableEventos.getModel();
        
        for (Map.Entry<Integer, Map<Integer, Evento> > m: eventos.entrySet()) {
            for (Map.Entry<Integer, Evento> m2: m.getValue().entrySet()) {
                idAposta = m.getKey();
                evento = m2.getValue();
                ganho = this.betEss.getGanhoEmAposta(m.getKey());
                
                model.addRow(new Object[] {
                    idAposta,
                    m2.getKey(),
                    evento.getEquipaUm(),
                    evento.getEquipaDois(),
                    evento.getResultado(),
                    this.betEss.getResultadoApostado(idAposta, evento),
                    ganho
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabel_BetESS_Logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));

        jPanelMenu.setBackground(new java.awt.Color(255, 102, 102));
        jPanelMenu.setToolTipText("[97,212,195]");
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_BetESS_Logo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_BetESS_Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BetESS_Logo.setText("BetESS");
        jPanelMenu.add(jLabel_BetESS_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Aposta", "ID Evento", "Equipa 1", "Equipa 2", "Resultado", "Resultado Apostado", "Ganho na aposta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEventos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEventos);

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notificações");

        okBtn.setForeground(new java.awt.Color(102, 102, 102));
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(701, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(okBtn)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.betEss.limpaNotifications(this.estatuto);
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_BetESS_Logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableEventos;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
