package betess.presentation;

import betess.business.BetESS;
import betess.business.PassErradaException;
import betess.business.EmailErradoException;
import betess.business.RegistoInvalidoException;

/**
 * LoginFrame => Interface do menu de login da aplicação.
 *
 * @author Manuel Sousa
 * @author Tiago Alves
 */
public class LoginFrame extends javax.swing.JFrame {

    private BetESS betEss;
    
    /**
     * Construtor de um novo LoginFrame.
     * 
     * @param betEss
     */
    public LoginFrame(BetESS betEss) {
        initComponents();
        this.betEss = betEss;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel_BetESS_Logo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        nomeTextField = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel_RegistarBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Registar = new javax.swing.JLabel();
        jLabel_Login = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setToolTipText("[97,212,195]");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 220, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 280, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel_BetESS_Logo.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel_BetESS_Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BetESS_Logo.setText("BetESS");
        jPanel2.add(jLabel_BetESS_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 567));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Login ou Registo");

        jLabel_Nome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Nome.setText("NOME COMPLETO");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        passwordField.setBackground(new java.awt.Color(36, 47, 65));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("jPasswordField");
        passwordField.setBorder(null);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });

        nomeTextField.setBackground(new java.awt.Color(36, 47, 65));
        nomeTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nomeTextField.setForeground(new java.awt.Color(255, 255, 255));
        nomeTextField.setText("Introduza o seu nome completo");
        nomeTextField.setBorder(null);
        nomeTextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        nomeTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeTextFieldMouseClicked(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(36, 47, 65));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Concordo com os termos e condições");

        jPanel_RegistarBtn.setBackground(new java.awt.Color(255, 102, 102));
        jPanel_RegistarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_RegistarBtnMouseClicked(evt);
            }
        });
        jPanel_RegistarBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("EMAIL");
        jPanel_RegistarBtn.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel_Registar.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Registar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Registar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registar.setText("Registar");
        jPanel_RegistarBtn.add(jLabel_Registar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel_Login.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setText("Já sou membro");
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Password.setText("PASSWORD");

        jLabel_Email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_Email.setText("EMAIL");

        emailTextField.setBackground(new java.awt.Color(36, 47, 65));
        emailTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setText("Introduza o seu Email");
        emailTextField.setBorder(null);
        emailTextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel_RegistarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Login)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel_Nome)
                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox1)
                                .addComponent(jLabel_Password)
                                .addComponent(jLabel_Email)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 85, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jLabel_Nome)
                .addGap(18, 18, 18)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel_Password)
                .addGap(12, 12, 12)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_Login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_RegistarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 0, 430, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_passwordFieldFocusGained

    private void nomeTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeTextFieldMouseClicked
        // TODO add your handling code here:
        nomeTextField.setText("");
    }//GEN-LAST:event_nomeTextFieldMouseClicked

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
        emailTextField.setText("");
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked
        String user = emailTextField.getText();
        char[] arrayPass = passwordField.getPassword();
        String password = String.valueOf(arrayPass);
        
        int estatuto = -1;

        try {
            estatuto = this.betEss.login(user, password);
        } catch (EmailErradoException | PassErradaException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Dados inválidos!", "Login", 0);
        }
        
        if (estatuto == 0) {
            MenuAdmin menu = new MenuAdmin(this.betEss);
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.dispose();
        } else if (estatuto == 1) {
            MenuApostador menu = new MenuApostador(this.betEss);
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jPanel_RegistarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_RegistarBtnMouseClicked
        toFront(); // Envia panel para a frente de Label "Registar"
        
        String nome = nomeTextField.getText();
        String email = emailTextField.getText();
        char[] arrayPass = passwordField.getPassword();
        String password = String.valueOf(arrayPass);
        
        try {
            this.betEss.registo(email, nome, password, 0);
            javax.swing.JOptionPane.showMessageDialog(this, "Registo efetuado com sucesso!", "Registo", 1); // Futuramente mudar icon!
        } catch (RegistoInvalidoException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Dados inválidos!", "Registo", 0);
        }
    }//GEN-LAST:event_jPanel_RegistarBtnMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BetESS_Logo;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Registar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_RegistarBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
