package betess.presentation;

import betess.business.Aposta;
import betess.business.Apostador;
import betess.business.BetESS;
import betess.business.Evento;
import java.awt.Color;
import java.util.Collection;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * MenuApostador => Interface do menu de um apostador da aplicação.
 *
 * @author Manuel Sousa
 * @author Tiago Alves
 */
public class MenuApostador extends javax.swing.JFrame {
    
    private BetESS betEss;
    private Aposta newAposta;
    private String user;
    
    /**
     * Construtor de um novo MenuApostador.
     * 
     * @param betEss
     */
    public MenuApostador(BetESS betEss) {
        this.betEss = betEss;
        this.newAposta = new Aposta();
        this.user = this.betEss.getUser();
        initComponents();
        
        // Adiciona Nome do Utilizador e Quantidade de Coins.
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogApostar = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textFieldCoins = new javax.swing.JTextField();
        BtnSubmeterCoins = new javax.swing.JButton();
        jDialogCarregarCoins = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        BtnCarregarCoins = new javax.swing.JButton();
        jComboBoxNCoins = new javax.swing.JComboBox<>();
        jPanel_BtnLogout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jLabel_BetESS_Logo = new javax.swing.JLabel();
        jPanelProfile = new javax.swing.JPanel();
        jLabelProfile = new javax.swing.JLabel();
        indProfile = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        indHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelAposta = new javax.swing.JPanel();
        jLabelAposta = new javax.swing.JLabel();
        indAposta = new javax.swing.JPanel();
        jPanelMinhasApostas = new javax.swing.JPanel();
        jLabelProfile1 = new javax.swing.JLabel();
        indMinhasApostas = new javax.swing.JPanel();
        jPanelMain_Home = new javax.swing.JPanel();
        jLabelHome_Nome = new javax.swing.JLabel();
        jLabelHome_Coins = new javax.swing.JLabel();
        jTextHome_Nome = new javax.swing.JTextField();
        jTextHome_Coins = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jPanelConsultarEvento = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelCarregarCoins = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelMain_Profile = new javax.swing.JPanel();
        jTextProfile_Nome = new javax.swing.JTextField();
        jTextProfile_Email = new javax.swing.JTextField();
        jTextProfile_Password = new javax.swing.JTextField();
        jTextProfile_Coins = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editaNomeBtn = new javax.swing.JButton();
        editaPassBtn = new javax.swing.JButton();
        editaEmailbtn = new javax.swing.JButton();
        confirmaNome = new javax.swing.JButton();
        confirmaEmail = new javax.swing.JButton();
        confirmaPass = new javax.swing.JButton();
        jPanelMain_Aposta = new javax.swing.JPanel();
        jPanelApostar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelRemEvento = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAposta = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ganhos = new javax.swing.JLabel();
        jPanelMain_MinhasApostas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMinhasApostas = new javax.swing.JTable();
        jPanelVerAposta = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jDialogApostar.setResizable(false);
        jDialogApostar.setSize(new java.awt.Dimension(376, 172));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setSize(new java.awt.Dimension(363, 177));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Número de ESSCoins a Apostar");

        BtnSubmeterCoins.setText("Submeter");
        BtnSubmeterCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmeterCoinsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(BtnSubmeterCoins)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSubmeterCoins)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogApostarLayout = new javax.swing.GroupLayout(jDialogApostar.getContentPane());
        jDialogApostar.getContentPane().setLayout(jDialogApostarLayout);
        jDialogApostarLayout.setHorizontalGroup(
            jDialogApostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogApostarLayout.setVerticalGroup(
            jDialogApostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogCarregarCoins.setMinimumSize(new java.awt.Dimension(363, 177));
        jDialogCarregarCoins.setResizable(false);
        jDialogCarregarCoins.setSize(new java.awt.Dimension(363, 177));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Número de Coins a Carregar");

        BtnCarregarCoins.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        BtnCarregarCoins.setText("Submeter Coins");
        BtnCarregarCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarCoinsActionPerformed(evt);
            }
        });

        jComboBoxNCoins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "50", "100", "500", "1000" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxNCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(133, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCarregarCoins)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxNCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCarregarCoins)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogCarregarCoinsLayout = new javax.swing.GroupLayout(jDialogCarregarCoins.getContentPane());
        jDialogCarregarCoins.getContentPane().setLayout(jDialogCarregarCoinsLayout);
        jDialogCarregarCoinsLayout.setHorizontalGroup(
            jDialogCarregarCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogCarregarCoinsLayout.setVerticalGroup(
            jDialogCarregarCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_BtnLogout.setBackground(new java.awt.Color(255, 102, 102));
        jPanel_BtnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_BtnLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BtnLogoutLayout = new javax.swing.GroupLayout(jPanel_BtnLogout);
        jPanel_BtnLogout.setLayout(jPanel_BtnLogoutLayout);
        jPanel_BtnLogoutLayout.setHorizontalGroup(
            jPanel_BtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BtnLogoutLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_BtnLogoutLayout.setVerticalGroup(
            jPanel_BtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BtnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel_BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 40));

        jPanelMenu.setBackground(new java.awt.Color(255, 102, 102));
        jPanelMenu.setToolTipText("[97,212,195]");
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_BetESS_Logo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_BetESS_Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BetESS_Logo.setText("BetESS");
        jPanelMenu.add(jLabel_BetESS_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        jPanelProfile.setBackground(new java.awt.Color(255, 102, 102));
        jPanelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelProfileMouseClicked(evt);
            }
        });

        jLabelProfile.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelProfile.setText("Profile");

        indProfile.setOpaque(false);
        indProfile.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout indProfileLayout = new javax.swing.GroupLayout(indProfile);
        indProfile.setLayout(indProfileLayout);
        indProfileLayout.setHorizontalGroup(
            indProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indProfileLayout.setVerticalGroup(
            indProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelProfileLayout = new javax.swing.GroupLayout(jPanelProfile);
        jPanelProfile.setLayout(jPanelProfileLayout);
        jPanelProfileLayout.setHorizontalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addComponent(indProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabelProfile)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelProfileLayout.setVerticalGroup(
            jPanelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanelProfileLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 50));

        jPanelHome.setBackground(new java.awt.Color(255, 102, 102));
        jPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Home");

        indHome.setOpaque(false);
        indHome.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout indHomeLayout = new javax.swing.GroupLayout(indHome);
        indHome.setLayout(indHomeLayout);
        indHomeLayout.setHorizontalGroup(
            indHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indHomeLayout.setVerticalGroup(
            indHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(indHome, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indHome, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelMenu.add(jPanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jPanelAposta.setBackground(new java.awt.Color(255, 102, 102));
        jPanelAposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelApostaMouseClicked(evt);
            }
        });

        jLabelAposta.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelAposta.setText("Aposta Atual");

        indAposta.setOpaque(false);
        indAposta.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout indApostaLayout = new javax.swing.GroupLayout(indAposta);
        indAposta.setLayout(indApostaLayout);
        indApostaLayout.setHorizontalGroup(
            indApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indApostaLayout.setVerticalGroup(
            indApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelApostaLayout = new javax.swing.GroupLayout(jPanelAposta);
        jPanelAposta.setLayout(jPanelApostaLayout);
        jPanelApostaLayout.setHorizontalGroup(
            jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApostaLayout.createSequentialGroup()
                .addComponent(indAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabelAposta)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelApostaLayout.setVerticalGroup(
            jPanelApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indAposta, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanelApostaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelAposta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelAposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 50));

        jPanelMinhasApostas.setBackground(new java.awt.Color(255, 102, 102));
        jPanelMinhasApostas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinhasApostasMouseClicked(evt);
            }
        });

        jLabelProfile1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelProfile1.setText("Minhas Apostas");

        indMinhasApostas.setOpaque(false);
        indMinhasApostas.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout indMinhasApostasLayout = new javax.swing.GroupLayout(indMinhasApostas);
        indMinhasApostas.setLayout(indMinhasApostasLayout);
        indMinhasApostasLayout.setHorizontalGroup(
            indMinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        indMinhasApostasLayout.setVerticalGroup(
            indMinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMinhasApostasLayout = new javax.swing.GroupLayout(jPanelMinhasApostas);
        jPanelMinhasApostas.setLayout(jPanelMinhasApostasLayout);
        jPanelMinhasApostasLayout.setHorizontalGroup(
            jPanelMinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinhasApostasLayout.createSequentialGroup()
                .addComponent(indMinhasApostas, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelProfile1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelMinhasApostasLayout.setVerticalGroup(
            jPanelMinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indMinhasApostas, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(jPanelMinhasApostasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelProfile1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanelMinhasApostas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 50));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, -1, 680));

        jPanelMain_Home.setBackground(new java.awt.Color(36, 47, 65));

        jLabelHome_Nome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHome_Nome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelHome_Nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome_Nome.setText("Nome");

        jLabelHome_Coins.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelHome_Coins.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome_Coins.setText("ESSCoins");

        jTextHome_Nome.setEditable(false);

        jTextHome_Coins.setEditable(false);

        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipa 1", "Equipa 2", "Odd 1", "Odd 2", "Odd X"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEventos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEventos);

        jPanelConsultarEvento.setBackground(new java.awt.Color(255, 102, 102));
        jPanelConsultarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConsultarEventoMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Consultar Evento");

        javax.swing.GroupLayout jPanelConsultarEventoLayout = new javax.swing.GroupLayout(jPanelConsultarEvento);
        jPanelConsultarEvento.setLayout(jPanelConsultarEventoLayout);
        jPanelConsultarEventoLayout.setHorizontalGroup(
            jPanelConsultarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(19, 19, 19))
        );
        jPanelConsultarEventoLayout.setVerticalGroup(
            jPanelConsultarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarEventoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelCarregarCoins.setBackground(new java.awt.Color(255, 102, 102));
        jPanelCarregarCoins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCarregarCoinsMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Carregar Coins");

        javax.swing.GroupLayout jPanelCarregarCoinsLayout = new javax.swing.GroupLayout(jPanelCarregarCoins);
        jPanelCarregarCoins.setLayout(jPanelCarregarCoinsLayout);
        jPanelCarregarCoinsLayout.setHorizontalGroup(
            jPanelCarregarCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarregarCoinsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelCarregarCoinsLayout.setVerticalGroup(
            jPanelCarregarCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarregarCoinsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMain_HomeLayout = new javax.swing.GroupLayout(jPanelMain_Home);
        jPanelMain_Home.setLayout(jPanelMain_HomeLayout);
        jPanelMain_HomeLayout.setHorizontalGroup(
            jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_HomeLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMain_HomeLayout.createSequentialGroup()
                        .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMain_HomeLayout.createSequentialGroup()
                                .addComponent(jLabelHome_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextHome_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMain_HomeLayout.createSequentialGroup()
                                .addComponent(jLabelHome_Coins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jTextHome_Coins, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMain_HomeLayout.createSequentialGroup()
                        .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMain_HomeLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jPanelConsultarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(jPanelCarregarCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(205, Short.MAX_VALUE))))
        );
        jPanelMain_HomeLayout.setVerticalGroup(
            jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMain_HomeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHome_Nome)
                    .addComponent(jTextHome_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHome_Coins)
                    .addComponent(jTextHome_Coins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMain_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConsultarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCarregarCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 0, 890, 680));

        jPanelMain_Profile.setBackground(new java.awt.Color(36, 47, 65));
        jPanelMain_Profile.setPreferredSize(new java.awt.Dimension(840, 617));

        jTextProfile_Nome.setEditable(false);
        jTextProfile_Nome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextProfile_Email.setEditable(false);
        jTextProfile_Email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextProfile_Password.setEditable(false);
        jTextProfile_Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextProfile_Coins.setEditable(false);
        jTextProfile_Coins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ESSCoins");

        editaNomeBtn.setText("Editar");
        editaNomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaNomeBtnActionPerformed(evt);
            }
        });

        editaPassBtn.setText("Editar");
        editaPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaPassBtnActionPerformed(evt);
            }
        });

        editaEmailbtn.setText("Editar");
        editaEmailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaEmailbtnActionPerformed(evt);
            }
        });

        confirmaNome.setText("Confirmar");
        confirmaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaNomeActionPerformed(evt);
            }
        });

        confirmaEmail.setText("Confirmar");
        confirmaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaEmailActionPerformed(evt);
            }
        });

        confirmaPass.setText("Confirmar");
        confirmaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMain_ProfileLayout = new javax.swing.GroupLayout(jPanelMain_Profile);
        jPanelMain_Profile.setLayout(jPanelMain_ProfileLayout);
        jPanelMain_ProfileLayout.setHorizontalGroup(
            jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextProfile_Coins, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextProfile_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProfile_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProfile_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                                .addComponent(editaNomeBtn)
                                .addGap(18, 18, 18)
                                .addComponent(confirmaNome))
                            .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                                .addComponent(editaEmailbtn)
                                .addGap(18, 18, 18)
                                .addComponent(confirmaEmail))
                            .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                                .addComponent(editaPassBtn)
                                .addGap(18, 18, 18)
                                .addComponent(confirmaPass))))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanelMain_ProfileLayout.setVerticalGroup(
            jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_ProfileLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextProfile_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editaNomeBtn)
                    .addComponent(confirmaNome))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editaEmailbtn)
                        .addComponent(confirmaEmail))
                    .addComponent(jTextProfile_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelMain_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextProfile_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editaPassBtn)
                    .addComponent(confirmaPass))
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextProfile_Coins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 890, 680));

        jPanelMain_Aposta.setBackground(new java.awt.Color(36, 47, 65));
        jPanelMain_Aposta.setPreferredSize(new java.awt.Dimension(840, 617));

        jPanelApostar.setBackground(new java.awt.Color(255, 102, 102));
        jPanelApostar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelApostarMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apostar!");

        javax.swing.GroupLayout jPanelApostarLayout = new javax.swing.GroupLayout(jPanelApostar);
        jPanelApostar.setLayout(jPanelApostarLayout);
        jPanelApostarLayout.setHorizontalGroup(
            jPanelApostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelApostarLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(31, 31, 31))
        );
        jPanelApostarLayout.setVerticalGroup(
            jPanelApostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApostarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelRemEvento.setBackground(new java.awt.Color(255, 102, 102));
        jPanelRemEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRemEventoMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Remover Evento");

        javax.swing.GroupLayout jPanelRemEventoLayout = new javax.swing.GroupLayout(jPanelRemEvento);
        jPanelRemEvento.setLayout(jPanelRemEventoLayout);
        jPanelRemEventoLayout.setHorizontalGroup(
            jPanelRemEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRemEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );
        jPanelRemEventoLayout.setVerticalGroup(
            jPanelRemEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemEventoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTableAposta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableAposta.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTableAposta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipa Casa", "Equipa Fora", "Odd Apostada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAposta);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ganhos Possíveis:");

        ganhos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ganhos.setForeground(new java.awt.Color(255, 255, 255));
        ganhos.setText(String.valueOf(this.newAposta.getValor())
        );

        javax.swing.GroupLayout jPanelMain_ApostaLayout = new javax.swing.GroupLayout(jPanelMain_Aposta);
        jPanelMain_Aposta.setLayout(jPanelMain_ApostaLayout);
        jPanelMain_ApostaLayout.setHorizontalGroup(
            jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_ApostaLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMain_ApostaLayout.createSequentialGroup()
                        .addGroup(jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jPanelApostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMain_ApostaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanelRemEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ganhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanelMain_ApostaLayout.setVerticalGroup(
            jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_ApostaLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMain_ApostaLayout.createSequentialGroup()
                        .addGroup(jPanelMain_ApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ganhos))
                        .addGap(40, 40, 40)
                        .addComponent(jPanelApostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelRemEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain_Aposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 890, 680));

        jPanelMain_MinhasApostas.setBackground(new java.awt.Color(36, 47, 65));
        jPanelMain_MinhasApostas.setPreferredSize(new java.awt.Dimension(840, 617));

        jTableMinhasApostas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTableMinhasApostas.setForeground(new java.awt.Color(255, 102, 102));
        jTableMinhasApostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador da Aposta", "Ganho Possivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableMinhasApostas);

        jPanelVerAposta.setBackground(new java.awt.Color(255, 102, 102));
        jPanelVerAposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelVerApostaMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ver Aposta");

        javax.swing.GroupLayout jPanelVerApostaLayout = new javax.swing.GroupLayout(jPanelVerAposta);
        jPanelVerAposta.setLayout(jPanelVerApostaLayout);
        jPanelVerApostaLayout.setHorizontalGroup(
            jPanelVerApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerApostaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(22, 22, 22))
        );
        jPanelVerApostaLayout.setVerticalGroup(
            jPanelVerApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerApostaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMain_MinhasApostasLayout = new javax.swing.GroupLayout(jPanelMain_MinhasApostas);
        jPanelMain_MinhasApostas.setLayout(jPanelMain_MinhasApostasLayout);
        jPanelMain_MinhasApostasLayout.setHorizontalGroup(
            jPanelMain_MinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_MinhasApostasLayout.createSequentialGroup()
                .addGroup(jPanelMain_MinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMain_MinhasApostasLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMain_MinhasApostasLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jPanelVerAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanelMain_MinhasApostasLayout.setVerticalGroup(
            jPanelMain_MinhasApostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMain_MinhasApostasLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanelVerAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain_MinhasApostas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 890, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_BtnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BtnLogoutMouseClicked
        this.betEss.endApp(); // Guarda o estado da aplicação.
        this.dispose();
        
        LoginFrame lf = new LoginFrame(this.betEss);
        
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
        lf.setFocusableWindowState(true);
    }//GEN-LAST:event_jPanel_BtnLogoutMouseClicked

    private void jPanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseClicked
        jPanelHome.setBackground(new Color(221, 85, 85));
        indHome.setOpaque(true);
        resetColor(new JPanel[] { jPanelProfile, jPanelAposta, jPanelMinhasApostas }, 
                   new JPanel[] { indProfile, indAposta, indMinhasApostas });
        
        jPanelMain_Profile.setVisible(false);
        jPanelMain_Home.setVisible(true);
        jPanelMain_Aposta.setVisible(false);
        jPanelMain_MinhasApostas.setVisible(false);
    }//GEN-LAST:event_jPanelHomeMouseClicked

    private void jPanelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProfileMouseClicked
        jPanelProfile.setBackground(new Color(221, 85, 85));
        indProfile.setOpaque(true);
        resetColor(new JPanel[] { jPanelHome, jPanelAposta, jPanelMinhasApostas }, 
                   new JPanel[] { indHome, indAposta, indMinhasApostas });
        
        jPanelMain_Home.setVisible(false);
        jPanelMain_Profile.setVisible(true);
        jPanelMain_Aposta.setVisible(false);
        jPanelMain_MinhasApostas.setVisible(false);
    }//GEN-LAST:event_jPanelProfileMouseClicked

    private void jPanelApostarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelApostarMouseClicked
        if (jTableAposta.getRowCount() == 0)
            javax.swing.JOptionPane.showMessageDialog(this, "Aposta Vazia!", "Aposta", 0);
        else {
            jDialogApostar.setVisible(true);
            jDialogApostar.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jPanelApostarMouseClicked
    
    private void jPanelApostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelApostaMouseClicked
        jPanelAposta.setBackground(new Color(221, 85, 85));
        indAposta.setOpaque(true);
        resetColor(new JPanel[] { jPanelHome, jPanelProfile, jPanelMinhasApostas }, 
                   new JPanel[] { indHome, indProfile, indMinhasApostas });
        
        setupApostaAtual();
        
        jPanelMain_Home.setVisible(false);
        jPanelMain_Profile.setVisible(false);
        jPanelMain_Aposta.setVisible(true);
        jPanelMain_MinhasApostas.setVisible(false);
    }//GEN-LAST:event_jPanelApostaMouseClicked

    private void jPanelConsultarEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultarEventoMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) jTableEventos.getModel();
            int index = jTableEventos.getSelectedRow();
            int idEvento = (int) model.getValueAt(index, 0);
        
            EventoDialog ed = new EventoDialog(this, true, this.betEss, idEvento, this.newAposta);
            ed.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum evento selecionado!", "Consulta", 0);
        }
    }//GEN-LAST:event_jPanelConsultarEventoMouseClicked

    private void jPanelMinhasApostasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinhasApostasMouseClicked
        jPanelMinhasApostas.setBackground(new Color(221, 85, 85));
        indMinhasApostas.setOpaque(true);
        resetColor(new JPanel[] { jPanelHome, jPanelProfile, jPanelAposta }, 
                   new JPanel[] { indHome, indProfile, indAposta });
        
        addAllApostasTable(this.betEss.getApostasUser(this.user));
        
        jPanelMain_Home.setVisible(false);
        jPanelMain_Profile.setVisible(false);
        jPanelMain_Aposta.setVisible(false);
        jPanelMain_MinhasApostas.setVisible(true);
    }//GEN-LAST:event_jPanelMinhasApostasMouseClicked

    private void jPanelCarregarCoinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCarregarCoinsMouseClicked
        jDialogCarregarCoins.setVisible(true);
        jDialogCarregarCoins.setLocationRelativeTo(null);
    }//GEN-LAST:event_jPanelCarregarCoinsMouseClicked

    private void BtnSubmeterCoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmeterCoinsActionPerformed
        try {
            double val = Double.parseDouble(textFieldCoins.getText());
            double totalCoinsUser = this.betEss.getApostador(this.user).getEssCoins();
            
            System.out.println(val);
            
            if (val <= 0 || val > totalCoinsUser) {
                javax.swing.JOptionPane.showMessageDialog(this, "Número de ESSCoins inválido!", "Submeter Aposta", 0);
                return;
            }
            
            // Insere uma cópia da nova aposta no respetivo user.
            this.betEss.novaAposta(this.user, val, this.newAposta.clone());
            this.newAposta = new Aposta();
            
            jDialogApostar.dispose();
        
            jPanelMinhasApostas.setBackground(new Color(221, 85, 85));
            indMinhasApostas.setOpaque(true);
            resetColor(new JPanel[] { jPanelHome, jPanelProfile, jPanelAposta }, 
                       new JPanel[] { indHome, indProfile, indAposta });
        
            addAllApostasTable(this.betEss.getApostasUser(this.user));
            
            // Número de ESSCoins em home é atualizado.
            jTextHome_Coins.setText("" + this.betEss.getApostador(this.user).getEssCoins());
            
            // Número de ESSCoins em profile é atualizado.
            jTextProfile_Coins.setText("" + this.betEss.getApostador(this.user).getEssCoins());
        
            jPanelMain_Home.setVisible(false);
            jPanelMain_Profile.setVisible(false);
            jPanelMain_Aposta.setVisible(false);
            jPanelMain_MinhasApostas.setVisible(true);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Número de ESSCoins inválido!", "Submeter Aposta", 0);
        }
    }//GEN-LAST:event_BtnSubmeterCoinsActionPerformed

    private void jPanelRemEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRemEventoMouseClicked
        try {    
            DefaultTableModel model = (DefaultTableModel) jTableAposta.getModel();
            int index = jTableAposta.getSelectedRow();
            int idEvento = (int) model.getValueAt(index, 0);

            // Determinar qual o evento selecionado.
            Evento e = this.betEss.getEvento(idEvento);

            // Remover evento selecionado da Aposta atual.
            this.newAposta.remEventoFromAposta(e);

            // Atualizar tabela de eventos.
            setupApostaAtual();
        } catch (ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum evento selecionado!", "Remover Evento", 0);
        }
    }//GEN-LAST:event_jPanelRemEventoMouseClicked

    private void BtnCarregarCoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarCoinsActionPerformed
        double coins = Double.parseDouble((String)jComboBoxNCoins.getSelectedItem());
        
        // Adiciona as coins carregadas ao total existente.
        this.betEss.getApostador(this.user).addTotalCoins(coins);
        
        // Atualizada as coins mostradas no menu Home.
        jTextHome_Coins.setText("" + this.betEss.getApostador(this.user).getEssCoins());
        
        //Atualizadas as coins mostradas no menu Profile
        jTextProfile_Coins.setText("" + this.betEss.getApostador(this.user).getEssCoins());
    }//GEN-LAST:event_BtnCarregarCoinsActionPerformed

    private void jPanelVerApostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVerApostaMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) this.jTableMinhasApostas.getModel();
            int index = jTableMinhasApostas.getSelectedRow();
            int idAposta = (int) model.getValueAt(index, 0);
        
            Aposta a = this.betEss.getApostador(user).getApostas().get(idAposta);
        
            DialogAposta da = new DialogAposta(this, true, this.betEss, a);
            da.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma Aposta Disponível!", "Ver Aposta", 0);
        }
    }//GEN-LAST:event_jPanelVerApostaMouseClicked

    private void editaEmailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaEmailbtnActionPerformed
        // Botão editar email.
        this.jTextProfile_Email.setEditable(true);
    }//GEN-LAST:event_editaEmailbtnActionPerformed

    private void editaNomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaNomeBtnActionPerformed
        // Botão editar nome.
        this.jTextProfile_Nome.setEditable(true);
    }//GEN-LAST:event_editaNomeBtnActionPerformed

    private void editaPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaPassBtnActionPerformed
        // Botão editar password.
        this.jTextProfile_Password.setEditable(true);
    }//GEN-LAST:event_editaPassBtnActionPerformed

    private void confirmaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaNomeActionPerformed
        String s = this.jTextProfile_Nome.getText();
        
        if (s != null) {
            this.betEss.editaNomeUser(s);
            this.updateProfile();
        }
    }//GEN-LAST:event_confirmaNomeActionPerformed

    private void confirmaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaEmailActionPerformed
        String s = this.jTextProfile_Email.getText();
        
        if (s != null) {
            this.betEss = this.betEss.editaMailUser(s);
            this.updateProfile();
        }
    }//GEN-LAST:event_confirmaEmailActionPerformed

    private void confirmaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaPassActionPerformed
        String s = this.jTextProfile_Password.getText();
        
        if (s != null) {
            this.betEss.editaPassUser(s);
            this.updateProfile();
        }
    }//GEN-LAST:event_confirmaPassActionPerformed
    
    
    /* ******************************* *
     * Conjunto de métodos auxiliares. *
     * ******************************* */
    
    public void setup() {
        Apostador a = this.betEss.getApostador(this.user);
        
        // Caixas de texto de Home
        jTextHome_Nome.setText(a.getNome());
        jTextHome_Coins.setText("" + a.getEssCoins());
        
        // Caixas de texto de Profile
        jTextProfile_Nome.setText(a.getNome());
        jTextProfile_Email.setText(a.getEmail());
        jTextProfile_Password.setText(a.getPassword());
        jTextProfile_Coins.setText("" + a.getEssCoins());
              
        // Adiciona todos os eventos existentes à JList.
        addAllEventosTable(this.betEss.getEventos().values());
        
        // Adiciona as apostas à tabela das minhas apostas.
        addAllApostasTable(this.betEss.getApostasUser(this.user));
        
        // Botão de home selecionada como predefinido.
        jPanelHome.setBackground(new Color(221, 85, 85));
        indHome.setOpaque(true);
        resetColor(new JPanel[] { jPanelProfile }, 
                   new JPanel[] { indProfile });
        
        // Menu de Profile não visível.
        jPanelMain_Profile.setVisible(false);
        
        // Menu de Aposta não visível.
        jPanelMain_Aposta.setVisible(false);
        
        // Menu de Minhas Apostas não visível.
        jPanelMain_MinhasApostas.setVisible(false);
    }
    
    private void updateProfile() {
        Apostador a = this.betEss.getApostador(this.user);
        
        // Caixas de texto de Profile
        jTextProfile_Nome.setText(a.getNome());
        jTextProfile_Nome.setEditable(false);
        jTextProfile_Email.setText(a.getEmail());
        jTextProfile_Email.setEditable(false);
        jTextProfile_Password.setText(a.getPassword());
        jTextProfile_Password.setEditable(false);
    }
    
    private void setupApostaAtual() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID");
        model.addColumn("Equipa Casa");
        model.addColumn("Equipa Fora");
        model.addColumn("Odd Apostada");
        //DefaultTableModel model = (DefaultTableModel) jTableAposta.getModel();
        
        this.newAposta.getEventos().values().forEach(e -> {
            model.addRow(new Object[] {
                e.getIdEvento(),
                e.getEquipaUm(),
                e.getEquipaDois(),
                this.newAposta.getOdds().get(e.getIdEvento())
            });
        });
        
        jTableAposta.setModel(model);
        
        double val = this.newAposta.getTotalOdds();
        ganhos.setText(String.valueOf(val) + " x ESSCoins apostadas.");      
    }
    
    private void resetColor(JPanel[] panels, JPanel[] indicators) {
        for (JPanel panel : panels) {
            panel.setBackground(new Color(255, 102, 102));
        } 
        
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
    }
    
    /**
     * Adiciona todos os eventos ativos à tabela.
     * @param eventos
     */
    public void addAllEventosTable(Collection<Evento> eventos) {
        DefaultTableModel model = (DefaultTableModel) jTableEventos.getModel();
        
        eventos.forEach(e -> {
            model.addRow(new Object[] {
                e.getIdEvento(), 
                e.getEquipaUm(),
                e.getEquipaDois(),
                e.getOddUm(),
                e.getOddDois(),
                e.getOddX()
            });
        });
    }
    
    public void addAllApostasTable(Collection<Aposta> apostas) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Identificador");
        model.addColumn("Ganho possível");
        
        apostas.forEach(a -> {
            model.addRow(new Object[] {
                a.getIdAposta(),
                a.getGanhoTotal()
            });
        });
        
        jTableMinhasApostas.setModel(model); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarregarCoins;
    private javax.swing.JButton BtnSubmeterCoins;
    private javax.swing.JButton confirmaEmail;
    private javax.swing.JButton confirmaNome;
    private javax.swing.JButton confirmaPass;
    private javax.swing.JButton editaEmailbtn;
    private javax.swing.JButton editaNomeBtn;
    private javax.swing.JButton editaPassBtn;
    private javax.swing.JLabel ganhos;
    private javax.swing.JPanel indAposta;
    private javax.swing.JPanel indHome;
    private javax.swing.JPanel indMinhasApostas;
    private javax.swing.JPanel indProfile;
    private javax.swing.JComboBox<String> jComboBoxNCoins;
    private javax.swing.JDialog jDialogApostar;
    private javax.swing.JDialog jDialogCarregarCoins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAposta;
    private javax.swing.JLabel jLabelHome_Coins;
    private javax.swing.JLabel jLabelHome_Nome;
    private javax.swing.JLabel jLabelProfile;
    private javax.swing.JLabel jLabelProfile1;
    private javax.swing.JLabel jLabel_BetESS_Logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAposta;
    private javax.swing.JPanel jPanelApostar;
    private javax.swing.JPanel jPanelCarregarCoins;
    private javax.swing.JPanel jPanelConsultarEvento;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMain_Aposta;
    private javax.swing.JPanel jPanelMain_Home;
    private javax.swing.JPanel jPanelMain_MinhasApostas;
    private javax.swing.JPanel jPanelMain_Profile;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMinhasApostas;
    private javax.swing.JPanel jPanelProfile;
    private javax.swing.JPanel jPanelRemEvento;
    private javax.swing.JPanel jPanelVerAposta;
    private javax.swing.JPanel jPanel_BtnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAposta;
    private javax.swing.JTable jTableEventos;
    private javax.swing.JTable jTableMinhasApostas;
    private javax.swing.JTextField jTextHome_Coins;
    private javax.swing.JTextField jTextHome_Nome;
    private javax.swing.JTextField jTextProfile_Coins;
    private javax.swing.JTextField jTextProfile_Email;
    private javax.swing.JTextField jTextProfile_Nome;
    private javax.swing.JTextField jTextProfile_Password;
    private javax.swing.JTextField textFieldCoins;
    // End of variables declaration//GEN-END:variables

}
