/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betess.presentation;

import betess.business.Aposta;
import betess.business.Evento;
import betess.business.Facade;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiagoalves
 */
public class MenuBookie extends javax.swing.JFrame {
    
    private Facade betEss;
    
    /**
     * Creates new form MenuBookie
     */
    public MenuBookie(Facade f) {
        this.betEss = f;
        initComponents();
        
        addAllEventosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jLabel_BetESS_Logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel_BtnLogout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jPanelCarregarBtn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelNovoEventobtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelAcompanharEventobtn = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1051, 680));
        setPreferredSize(new java.awt.Dimension(1051, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanelMenu.setBackground(new java.awt.Color(255, 102, 102));
        jPanelMenu.setToolTipText("[97,212,195]");
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_BetESS_Logo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_BetESS_Logo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BetESS_Logo.setText("BetESS");
        jPanelMenu.add(jLabel_BetESS_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 680));

        jPanel_BtnLogout.setBackground(new java.awt.Color(255, 102, 102));
        jPanel_BtnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_BtnLogoutMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betess/resources/icon-exit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_BtnLogoutLayout = new javax.swing.GroupLayout(jPanel_BtnLogout);
        jPanel_BtnLogout.setLayout(jPanel_BtnLogoutLayout);
        jPanel_BtnLogoutLayout.setHorizontalGroup(
            jPanel_BtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BtnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BtnLogoutLayout.setVerticalGroup(
            jPanel_BtnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BtnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("B");

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("O");

        jLabel3.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("O");

        jLabel4.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("K");

        jLabel5.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("I");

        jLabel6.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("E");

        jLabel8.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("E");

        jLabel9.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("W");

        jLabel10.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("E");

        jLabel11.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("C");

        jLabel12.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("L");

        jLabel13.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("M");

        jLabel14.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("O");

        jLabel15.setFont(new java.awt.Font("Avenir", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("!");

        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipa 1", "Equipa 2", "Odd 1", "Odd 2", "Odd X"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEventos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableEventos);

        jPanelCarregarBtn.setBackground(new java.awt.Color(255, 102, 102));
        jPanelCarregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCarregarBtnMouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Carregar Dados");

        javax.swing.GroupLayout jPanelCarregarBtnLayout = new javax.swing.GroupLayout(jPanelCarregarBtn);
        jPanelCarregarBtn.setLayout(jPanelCarregarBtnLayout);
        jPanelCarregarBtnLayout.setHorizontalGroup(
            jPanelCarregarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCarregarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(260, 260, 260))
        );
        jPanelCarregarBtnLayout.setVerticalGroup(
            jPanelCarregarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarregarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNovoEventobtn.setBackground(new java.awt.Color(255, 102, 102));
        jPanelNovoEventobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNovoEventobtnMouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Novo Evento");

        javax.swing.GroupLayout jPanelNovoEventobtnLayout = new javax.swing.GroupLayout(jPanelNovoEventobtn);
        jPanelNovoEventobtn.setLayout(jPanelNovoEventobtnLayout);
        jPanelNovoEventobtnLayout.setHorizontalGroup(
            jPanelNovoEventobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNovoEventobtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(268, 268, 268))
        );
        jPanelNovoEventobtnLayout.setVerticalGroup(
            jPanelNovoEventobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoEventobtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAcompanharEventobtn.setBackground(new java.awt.Color(255, 102, 102));
        jPanelAcompanharEventobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAcompanharEventobtnMouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Acompanhar Evento!");

        javax.swing.GroupLayout jPanelAcompanharEventobtnLayout = new javax.swing.GroupLayout(jPanelAcompanharEventobtn);
        jPanelAcompanharEventobtn.setLayout(jPanelAcompanharEventobtnLayout);
        jPanelAcompanharEventobtnLayout.setHorizontalGroup(
            jPanelAcompanharEventobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAcompanharEventobtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(244, 244, 244))
        );
        jPanelAcompanharEventobtnLayout.setVerticalGroup(
            jPanelAcompanharEventobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAcompanharEventobtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addComponent(jPanelCarregarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAcompanharEventobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelNovoEventobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelCarregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNovoEventobtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAcompanharEventobtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_BtnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BtnLogoutMouseClicked
        this.betEss.endApp(); // Guarda o estado da aplicação.
        this.dispose();

        LoginFrame lf = new LoginFrame(this.betEss);

        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
        lf.setFocusableWindowState(true);
    }//GEN-LAST:event_jPanel_BtnLogoutMouseClicked

    private void jPanelCarregarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCarregarBtnMouseClicked
        this.betEss.carregaEventos();
        this.addAllEventosTable();
    }//GEN-LAST:event_jPanelCarregarBtnMouseClicked

    private void jPanelNovoEventobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNovoEventobtnMouseClicked
        //botao novo evento
        DialogNovoEvento ne = new DialogNovoEvento(this, true, this.betEss);
        ne.setVisible(true);
        this.addAllEventosTable();
    }//GEN-LAST:event_jPanelNovoEventobtnMouseClicked

    private void jPanelAcompanharEventobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAcompanharEventobtnMouseClicked
        //botao acompanhar evento
        DefaultTableModel model = (DefaultTableModel) this.jTableEventos.getModel();
            int index = jTableEventos.getSelectedRow();
            int idEvento = (int) model.getValueAt(index, 0);
        
            if(this.betEss.novoInteresseEvento(idEvento)){
                javax.swing.JOptionPane.showMessageDialog(this, "A acompanhar evento!", "Evento", 1);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao tentar acompanhar evento! Lamentamos o incómodo :(", "Evento", 0);
            }
    }//GEN-LAST:event_jPanelAcompanharEventobtnMouseClicked

     /* ******************************* *
     * Conjunto de métodos auxiliares. *
     * ******************************* */
    
    public void addAllEventosTable() {
        DefaultTableModel model = (DefaultTableModel) jTableEventos.getModel();
        
        this.betEss.getEventos().values().forEach(e -> {
            model.addRow(new Object[] {
                e.getIdEvento(), 
                e.getEquipaUm(),
                e.getEquipaDois(),
                e.getOddUm(),
                e.getOddDois(),
                e.getOddX()
            });
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BetESS_Logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAcompanharEventobtn;
    private javax.swing.JPanel jPanelCarregarBtn;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNovoEventobtn;
    private javax.swing.JPanel jPanel_BtnLogout;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableEventos;
    // End of variables declaration//GEN-END:variables
}
